### ISSUE TITLE
Update to latest version of redline (1.2.2)

### ISSUE THREAD

**Issue by cawallin** [spaulg/redlinerpm-maven-plugin#1]
We're using this plugin for Presto (https://github.com/facebook/presto), and it's working great. However, we needed to update redline to work for rpm >= 4.11 (e.g., the version of rpm installed by default on Ubuntu 14.04) -- https://github.com/craigwblake/redline/pull/94.  Could you update redlinerpm-maven-plugin to the 1.2.2 release of redline? Sorry not to submit a patch, but I don't have corporate permission to commit to this repo.

**Comment by spaulg** [comment]
redlinerpm-maven-plugin v1.1 has been released with updated redline rpm and mvel dependencies.
Updated jars should be available via Central within 24 hours.

**Comment by cawallin** [comment]
Thanks!
